/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cerveceria_bd;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Year;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author luis hernandez
 */
public class Interfaz_Vendedor extends javax.swing.JFrame {
    
    conexion cc = new conexion();
    Connection cn = cc.MiConexion();
    
    DatosCompra[] datosCompra;
    int totalventa = 0;

    /**
     * Creates new form vendedor
     */
    public Interfaz_Vendedor() {
        initComponents();
        datosCompra = new DatosCompra[30];
        llenar();
        llenarComboBox();
        jButton1.setEnabled(false);
        jButton3.setEnabled(false);
        jButton9.setEnabled(false);
    }
    
    void llenarComboBox() {
        
        String sql = "SELECT nombre FROM producto";
        txtCantidadSolicitada.setText("");
        txtSubtotalVenderInformacion.setText("");
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            jComboBox2.addItem("Seleccione un producto");
            int con = 0;
            while (rs.next()) {
                jComboBox2.addItem(rs.getString("nombre"));
            }
            
        } catch (Exception e) {
        }
    }
    
    void llenar() {
        DatosCompra da = new DatosCompra();
        da.setCantS(-1);
        da.setCantS(-1);
        da.setIdproducto(-1);
        da.setNom("%");
        da.setSub_total(-1);
        da.setPrecio_venta(-1);
        for (int i = 0; i < 30; i++) {
            datosCompra[i] = da;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jComboBox2Dia2 = new javax.swing.JComboBox<>();
        jComboBox3Mes2 = new javax.swing.JComboBox<>();
        jComboBox4Año2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtCanti = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        txtPrecioVentaInformacion = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtSubtotalVenderInformacion = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtCantidadDisponibleInformacion = new javax.swing.JTextField();
        txtCantidadSolicitada = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton9 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton2.setText("Cerrar Sesion");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("REALIZAR VENTA"));

        jLabel2.setText("Celular:");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jLabel1.setText("Identifiacion Cliente: ");

        jTextField2.setText(" ");

        jLabel4.setText("Nombre:");

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });

        jLabel30.setText("FECHA");

        jComboBox2Dia2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIA", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        jComboBox2Dia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2Dia2ActionPerformed(evt);
            }
        });

        jComboBox3Mes2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MES", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        jComboBox3Mes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3Mes2ActionPerformed(evt);
            }
        });

        jComboBox4Año2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AÑO", "2018", "2019", "2020", "2021", "2022", "2023" }));
        jComboBox4Año2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4Año2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(49, 49, 49)
                        .addComponent(jComboBox2Dia2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3Mes2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox4Año2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jComboBox2Dia2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox3Mes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4Año2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton1.setText("Agregar A La Factura");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtCanti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantiActionPerformed(evt);
            }
        });
        txtCanti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantiKeyReleased(evt);
            }
        });

        jLabel24.setText("CANTIDAD");

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("INFORMACION DEL PRODUCTO"));

        jLabel26.setText("PRECIO DE VENTA ");

        txtPrecioVentaInformacion.setEditable(false);

        jLabel27.setText("SUB TOTAL A VENDER");

        txtSubtotalVenderInformacion.setEditable(false);
        txtSubtotalVenderInformacion.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtSubtotalVenderInformacionComponentAdded(evt);
            }
        });
        txtSubtotalVenderInformacion.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSubtotalVenderInformacionPropertyChange(evt);
            }
        });

        jLabel28.setText("CANTIDAD DISPONIBLE");

        jLabel29.setText("CANTIDAD SOLICITADA");

        txtCantidadDisponibleInformacion.setEditable(false);

        txtCantidadSolicitada.setEditable(false);

        jTextField6.setEditable(false);
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField6KeyReleased(evt);
            }
        });

        jLabel23.setText("ID PRODUCTO");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSubtotalVenderInformacion)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(txtCantidadDisponibleInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCantidadSolicitada, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                            .addComponent(txtPrecioVentaInformacion)
                            .addComponent(jTextField6))))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtCantidadDisponibleInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtCantidadSolicitada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecioVentaInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSubtotalVenderInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel25.setText("NOMBRE");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel24))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2, 0, 218, Short.MAX_VALUE)
                            .addComponent(txtCanti))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createTitledBorder("FACTURA"));
        jScrollPane3.setViewportView(jTextArea1);

        jPanel14.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 1, 420, 450));

        jButton9.setText("FINALIZAR VENTA");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 450, 240, 50));

        jButton3.setText("CANCELAR VENTA");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel14.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 190, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    String factura() {
        String mensaje = " _______________________________________________________\n"
                + " ------------------------------ LICORERA --------------------------------\n"
                + " -----------------------------------------------------------------------------\n"
                + "                          INFORMACION DEL CLIENTE\n"
                + "  NOMBRE  --- " + jTextField1.getText() + "\n"
                + "  CELULAR --- " + jTextField2.getText() + "\n"
                + " -----------------------------------------------------------------------------\n"
                + "                        INFORMACION DE LA COMPRA\n";
        for (int i = 0; i < 30; i++) {
            if (datosCompra[i].getCantS() != -1) {
                mensaje += " NOMBRE PRODUCTO -------- " + datosCompra[i].getNom() + "\n"
                        + " CANTIDAD A COMPRAR: ---- " + datosCompra[i].getCantS() + "\n"
                        + " PRECIO PRODUCTO ---------- " + datosCompra[i].getPrecio_venta() + "\n"
                        + " SUB TOTAL --------------------- " + datosCompra[i].getSub_total() + "\n"
                        + " -----------------------------------------------------------------------------\n";
            }
        }
        
        return mensaje += ""
                + " *******************************************************\n"
                + " TOTAL A PAGAR --------------- " + totalventa + "\n"
                + " *******************************************************\n"
                + " -----------------------------------------------------------------------------\n"
                + "                            GRACIAS POR ELEGIRNOS\n"
                + "                                   VUELVA PRONTO\n"
                + " -----------------------------------------------------------------------------";
    }
    int pos = 0;
    
    boolean igualfactura(int idfactura) {
        
        String sql = "SELECT idfacturaventa FROM facturaventa";
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            int id = 0;
            while (rs.next()) {
                id = Integer.parseInt(rs.getString("idfacturaventa"));
                if (id == idfactura) {
                    return true;
                }
            }
        } catch (Exception e) {
        }
        return false;
    }
    int factura_Venta;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Interfaz_Usuario iu = new Interfaz_Usuario();
        iu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        jTextField1.setText(jTextField1.getText().toUpperCase());
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
        // TODO add your handling code here:
        String[] producto = new String[3];
        String sql = "SELECT idcliente,nombre,telefono FROM cliente where idcliente='" + jTextField3.getText() + "'";
        
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                producto[0] = rs.getString("idcliente");
                producto[1] = rs.getString("nombre");
                producto[2] = rs.getString("telefono");
            }
            jTextField1.setText(producto[1]);
            jTextField2.setText(producto[2]);
            jTextField1.setEditable(false);
            jTextField2.setEditable(false);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "no");
        }
        
        if (jTextField1.getText().equals("")) {
            jTextField1.setEditable(true);
            jTextField2.setEditable(true);
        }
    }//GEN-LAST:event_jTextField3KeyReleased

    private void jComboBox2Dia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2Dia2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2Dia2ActionPerformed

    private void jComboBox3Mes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3Mes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3Mes2ActionPerformed

    private void jComboBox4Año2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4Año2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4Año2ActionPerformed
    String fechaVenta = "";
    boolean vendiendo = false;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String dia = jComboBox2Dia2.getSelectedItem().toString(), mes = jComboBox3Mes2.getSelectedItem().toString(), año = jComboBox4Año2.getSelectedItem().toString();
        
        if (dia.equals("DIA") || mes.equals("MES") || año.equals("AÑO")) {
            JOptionPane.showMessageDialog(null, "Seleccione una fecha por favor");
            return;
        }
        
        fechaVenta = año + "-" + mes + "-" + dia;
        
        jComboBox2Dia2.setEnabled(false);
        jComboBox3Mes2.setEnabled(false);
        jComboBox4Año2.setEnabled(false);
        
        vendiendo = true;
        
        if (factura_Venta == 0) {
            
            factura_Venta = (int) Math.floor(Math.random() * (1000 - 9999 + 1) + 9999);  // Valor entre M y N, ambos incluidos.

            while (igualfactura(factura_Venta)) {
                factura_Venta = (int) Math.floor(Math.random() * (1000 - 9999 + 1) + 9999);  // Valor entre M y N, ambos incluidos.
                JOptionPane.showMessageDialog(null, "while" + factura_Venta);
            }
        }
        int id = Integer.parseInt(jTextField6.getText());
        
        for (int i = 0; i < 30; i++) {
            if (datosCompra[i].getIdproducto() == id) {
                JOptionPane.showMessageDialog(null, "Ya este producto ha sido registrado en la factura");
                return;
            }
        }
        
        DatosCompra da = new DatosCompra();
        
        da.setIdproducto(id);
        da.setCantS(Integer.parseInt(txtCantidadSolicitada.getText()));
        da.setCantD(Integer.parseInt(txtCantidadDisponibleInformacion.getText()));
        da.setPrecio_venta(Integer.parseInt(txtPrecioVentaInformacion.getText()));
        da.setNom(String.valueOf(jComboBox2.getSelectedItem()));
        da.setSub_total(Integer.parseInt(txtSubtotalVenderInformacion.getText()));
        totalventa += da.getSub_total();
        
        datosCompra[pos] = da;
        pos++;
        limpiar();
        jTextArea1.setText(facturaVenta());
        jButton9.setEnabled(true);
        jButton3.setEnabled(true);
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtCantiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantiActionPerformed

    private void txtCantiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantiKeyReleased
        // TODO add your handling code here:
        String d = txtCantidadDisponibleInformacion.getText();
        if (!d.equals("")) {
            try {
                txtCantidadSolicitada.setText(txtCanti.getText());
                int cantSoli = Integer.parseInt(txtCantidadSolicitada.getText());
                int cantDis = Integer.parseInt(txtCantidadDisponibleInformacion.getText());
                
                if (cantSoli <= cantDis) {
                    
                    int subVender = Integer.parseInt(txtPrecioVentaInformacion.getText()) * cantSoli;
                    txtSubtotalVenderInformacion.setText(subVender + "");
                    
                    jButton1.setEnabled(true);
                } else {
                    
                    JOptionPane.showMessageDialog(null, "La cantidad solicitada sobrepasa la cantidad en disponible");
                    jButton1.setEnabled(false);
                    txtCanti.setText("");
                }
            } catch (Exception e) {
                txtCanti.setText("");
                txtCantidadSolicitada.setText("");
            }
            
        }

    }//GEN-LAST:event_txtCantiKeyReleased

    private void txtSubtotalVenderInformacionComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtSubtotalVenderInformacionComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalVenderInformacionComponentAdded

    private void txtSubtotalVenderInformacionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSubtotalVenderInformacionPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalVenderInformacionPropertyChange

    private void jTextField6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6KeyReleased

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        String[] producto = new String[4];
        String sql = "SELECT idproducto,precioventa,preciocompra,cantidad_Disponible FROM producto where nombre='" + jComboBox2.getSelectedItem() + "'";
        txtCantidadSolicitada.setText("");
        txtSubtotalVenderInformacion.setText("");
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                producto[0] = rs.getString("idproducto");
                producto[1] = rs.getString("precioventa");
                producto[2] = rs.getString("preciocompra");
                producto[3] = rs.getString("cantidad_Disponible");
            }
            
            jTextField6.setText(producto[0]);
            txtPrecioVentaInformacion.setText(producto[1]);
            txtCantidadDisponibleInformacion.setText(producto[3]);
            txtCanti.setEditable(true);
        } catch (Exception e) {
        }

    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

        try {
            String sql = "";
            sql = "INSERT INTO CLIENTE (idcliente,nombre,telefono) VALUES(" + "'" + jTextField3.getText() + "','" + jTextField1.getText() + "','" + jTextField2.getText() + "')";
            PreparedStatement psz = cn.prepareStatement(sql);
            int n;
            n = psz.executeUpdate();
            
        } catch (Exception e) {
            
        }
        
        try {
            
            String sql = "";
            sql = "INSERT INTO facturaventa (idfacturaventa,fecha,costoventa) VALUES(" + "'" + factura_Venta + "','" + fechaVenta + "','" + totalventa + "')";
            PreparedStatement psz = cn.prepareStatement(sql);
            int n;
            n = psz.executeUpdate();
            if (n > 0) {
                
            }
            
        } catch (Exception e) {
            
        }
        
        try {
            for (int i = 0; i < 30; i++) {
                if (datosCompra[i].getIdproducto() != -1) {
                    String sql = "";
                    sql = "INSERT INTO compra (idproducto,idcliente,idfacturaventa) VALUES(" + ""
                            + "'" + datosCompra[i].getIdproducto() + "','" + Integer.parseInt(jTextField3.getText()) + "',"
                            + "'" + factura_Venta + "')";
                    PreparedStatement psz = cn.prepareStatement(sql);
                    int n;
                    n = psz.executeUpdate();
                }
            }
        } catch (Exception e) {
        }
        
        try {
            int cantD = 0, cantS = 0;
            for (int i = 0; i < 30; i++) {
                if (datosCompra[i].getCantS() != -1) {
                    cantS = datosCompra[i].getCantS();
                    cantD = datosCompra[i].getCantD();
                    if (cantD > cantS) {
                        int cantF = cantD - cantS;
                        String sql = "UPDATE producto SET cantidad_Disponible = '" + cantF + "' WHERE producto.idproducto='" + datosCompra[i].getIdproducto() + "'";
                        PreparedStatement psz = cn.prepareStatement(sql);
                        int n = psz.executeUpdate();
                    }
                }
            }
            
            vendiendo = false;
            limpiar();
            jTextField3.setEditable(true);
            jButton9.setEnabled(false);
            jButton3.setEnabled(false);
            fechaVenta = "";
            factura_Venta = 0;
        } catch (Exception e) {
        }
        
        llenar();
        jTextArea1.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        llenar();
        jTextArea1.setText("");
        vendiendo = false;
        jButton3.setEnabled(false);
        jButton9.setEnabled(false);
        limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed
    String facturaVenta() {
        String mensaje = " _______________________________________________________\n"
                + " ------------------------------ LICORERA --------------------------------\n"
                + " -----------------------------------------------------------------------------\n"
                + "                          INFORMACION DEL CLIENTE\n"
                + "  NOMBRE  --- " + jTextField1.getText() + "\n"
                + "  CELULAR --- " + jTextField2.getText() + "\n"
                + " -----------------------------------------------------------------------------\n"
                + "                        INFORMACION DE LA COMPRA\n";
        for (int i = 0; i < 30; i++) {
            if (datosCompra[i].getCantS() != -1) {
                mensaje += " NOMBRE PRODUCTO -------- " + datosCompra[i].getNom() + "\n"
                        + " CANTIDAD A COMPRAR: ---- " + datosCompra[i].getCantS() + "\n"
                        + " PRECIO PRODUCTO ---------- " + datosCompra[i].getPrecio_venta() + "\n"
                        + " SUB TOTAL --------------------- " + datosCompra[i].getSub_total() + "\n"
                        + " -----------------------------------------------------------------------------\n";
            }
        }
        
        return mensaje += ""
                + " *******************************************************\n"
                + " ID FACTURA -------------------- " + factura_Venta + "\n"
                + " TOTAL A PAGAR --------------- " + totalventa + "\n"
                + " *******************************************************\n"
                + " -----------------------------------------------------------------------------\n"
                + "                            GRACIAS POR ELEGIRNOS\n"
                + "                                   VUELVA PRONTO\n"
                + " -----------------------------------------------------------------------------";
    }
    
    void limpiar() {
        
        jTextField6.setText("");
        txtCanti.setText("");
        jComboBox2.setSelectedIndex(0);
        txtCantidadDisponibleInformacion.setText("");
        txtPrecioVentaInformacion.setText("");
        txtSubtotalVenderInformacion.setText("");
        txtCantidadSolicitada.setText("");
        if (!vendiendo) {
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            jComboBox2Dia2.setSelectedIndex(0);
            jComboBox3Mes2.setSelectedIndex(0);
            jComboBox4Año2.setSelectedIndex(0);
            
            jComboBox2Dia2.setEnabled(true);
            jComboBox3Mes2.setEnabled(true);
            jComboBox4Año2.setEnabled(true);
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Vendedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox2Dia2;
    private javax.swing.JComboBox<String> jComboBox3Mes2;
    private javax.swing.JComboBox<String> jComboBox4Año2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField txtCanti;
    private javax.swing.JTextField txtCantidadDisponibleInformacion;
    private javax.swing.JTextField txtCantidadSolicitada;
    private javax.swing.JTextField txtPrecioVentaInformacion;
    private javax.swing.JTextField txtSubtotalVenderInformacion;
    // End of variables declaration//GEN-END:variables
}
